definitions:
  models.Article:
    properties:
      author:
        $ref: '#/definitions/models.Person'
      body:
        type: string
      create_at:
        type: string
      id:
        type: integer
      title:
        type: string
    type: object
  models.ArticleCreate:
    properties:
      author:
        $ref: '#/definitions/models.Person'
      body:
        type: string
      title:
        type: string
    type: object
  models.ArticleReq:
    properties:
      author:
        $ref: '#/definitions/models.Person'
      body:
        type: string
      id:
        type: integer
      title:
        type: string
    type: object
  models.DefaultError:
    properties:
      message:
        type: string
    type: object
  models.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  models.Person:
    properties:
      firstname:
        type: string
      lastname:
        type: string
    type: object
  models.SuccessResponse:
    properties:
      data: {}
      message:
        type: string
    type: object
info:
  contact: {}
  description: this is a sample article demo
  termsOfService: https://udevs.io
paths:
  /articles:
    get:
      consumes:
      - application/json
      description: API for get all article
      parameters:
      - description: offset
        in: path
        name: offset
        type: integer
      - description: limit
        in: path
        name: limit
        type: integer
      - description: search
        in: path
        name: search
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/models.Article'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.DefaultError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.DefaultError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.DefaultError'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/models.DefaultError'
      summary: Get All
      tags:
      - article
    post:
      consumes:
      - application/json
      description: API for creating article
      parameters:
      - description: article
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/models.ArticleCreate'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/models.SuccessResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/models.DefaultError'
      summary: Create article
      tags:
      - article
    put:
      consumes:
      - application/json
      description: API for updating articles
      parameters:
      - description: article
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/models.ArticleReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.DefaultError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.DefaultError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.DefaultError'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/models.DefaultError'
      summary: Update Article
      tags:
      - article
  /articles/{id}:
    delete:
      consumes:
      - application/json
      description: API for delete by id article
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.DefaultError'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/models.DefaultError'
      summary: Delete By Id
      tags:
      - article
    get:
      consumes:
      - application/json
      description: API for get by id article
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Article'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.DefaultError'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/models.DefaultError'
      summary: Get By Id
      tags:
      - article
swagger: "2.0"
